from __future__ import annotations

from datetime import datetime, timedelta

NOW = datetime.utcnow()

VK_MOCK = [
    {
        "id": 3,
        "platform": "vk",
        "title": "Результаты A/B тестирования сторис за месяц",
        "url": "https://instagram.com/p/example3",
        "author": "Content Creator",
        "published_at": (NOW - timedelta(days=1)).isoformat(),
        "views": 25400,
        "likes": 2100,
        "comments": 156,
        "engagement_rate_percent": 0.089,
        "sentiment": 0.68,
        "tags": ["ab-testing", "stories", "results"],
        "status": "active",
    },
    {
        "id": 4,
        "platform": "vk",
        "title": "Кейс: автоматизация отчетности для клиента из FinTech",
        "url": "https://vk.com/posts/example4",
        "author": "BD Manager",
        "published_at": (NOW - timedelta(days=7)).isoformat(),
        "views": 8700,
        "likes": 320,
        "comments": 45,
        "engagement_rate_percent": 0.042,
        "sentiment": 0.81,
        "tags": ["fintech", "case-study", "automation"],
        "status": "active",
    },
    {
        "id": 7,
        "platform": "vk",
        "title": "Опрос: какие метрики вы отслеживаете ежедневно?",
        "url": "https://vk.com/wall-123456_789",
        "author": "Community Manager",
        "published_at": (NOW - timedelta(hours=12)).isoformat(),
        "views": 5600,
        "likes": 290,
        "comments": 78,
        "engagement_rate_percent": 0.066,
        "sentiment": 0.42,
        "tags": ["poll", "metrics", "community"],
        "status": "active",
    },
]

TG_MOCK = [
    {
        "id": 10,
        "platform": "telegram",
        "title": "Новый интеграции: Google Analytics + Webda",
        "url": "https://t.me/example/10",
        "author": "Tech Lead",
        "published_at": (NOW - timedelta(hours=6)).isoformat(),
        "views": 7600,
        "likes": 420,
        "comments": 56,
        "engagement_rate_percent": 0.063,
        "sentiment": 0.71,
        "tags": ["integration", "google-analytics", "technical"],
        "status": "active",
    },
    {
        "id": 6,
        "platform": "telegram",
        "title": "Как увеличить охваты без бюджета на рекламу",
        "url": "https://t.me/example/6",
        "author": "Growth Hacker",
        "published_at": (NOW - timedelta(days=4)).isoformat(),
        "views": 12400,
        "likes": 680,
        "comments": 134,
        "engagement_rate_percent": 0.066,
        "sentiment": 0.58,
        "tags": ["growth", "organic", "tips"],
        "status": "active",
    },
    {
        "id": 2,
        "platform": "telegram",
        "title": "Боль контент-менеджера: ручная статистика",
        "url": "https://t.me/example/2",
        "author": "SMM",
        "published_at": (NOW - timedelta(days=5)).isoformat(),
        "views": 8900,
        "likes": 430,
        "comments": 95,
        "engagement_rate_percent": 0.059,
        "sentiment": 0.35,
        "tags": ["pain", "manual"],
        "status": "active",
    },
]

YOUTUBE_MOCK = [
    {
        "id": 1,
        "platform": "youtube",
        "title": "Как мы запустили умный реестр контента",
        "url": "https://example.com/youtube/1",
        "author": "Marketing Team",
        "published_at": (NOW - timedelta(days=3)).isoformat(),
        "views": 15230,
        "likes": 1230,
        "comments": 210,
        "engagement_rate_percent": 0.095,
        "sentiment": 0.72,
        "tags": ["webda", "case", "analytics"],
        "status": "active",
    },
    {
        "id": 5,
        "platform": "youtube",
        "title": "Обзор новых фич аналитики в Webda v2.1",
        "url": "https://example.com/youtube/5",
        "author": "Product Team",
        "published_at": (NOW - timedelta(days=2)).isoformat(),
        "views": 18300,
        "likes": 1450,
        "comments": 89,
        "engagement_rate_percent": 0.084,
        "sentiment": 0.75,
        "tags": ["product-update", "analytics", "webda"],
        "status": "active",
    },
    {
        "id": 8,
        "platform": "youtube",
        "title": "Тред: 5 ошибок при анализе контентной стратегии",
        "url": "https://example.com/youtube/8",
        "author": "Content Strategist",
        "published_at": (NOW - timedelta(days=6)).isoformat(),
        "views": 9200,
        "likes": 510,
        "comments": 67,
        "engagement_rate_percent": 0.063,
        "sentiment": 0.49,
        "tags": ["thread", "mistakes", "strategy"],
        "status": "active",
    },
    {
        "id": 9,
        "platform": "youtube",
        "title": "Интервью с CEO о будущем контентной аналитики",
        "url": "https://example.com/youtube/9",
        "author": "CEO",
        "published_at": (NOW - timedelta(days=10)).isoformat(),
        "views": 28700,
        "likes": 1980,
        "comments": 210,
        "engagement_rate_percent": 0.076,
        "sentiment": 0.85,
        "tags": ["interview", "ceo", "future"],
        "status": "active",
    },
]
